# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fcm' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fcm
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'fcmTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'fcm-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fcm-tvOS

  target 'fcm-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
